<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Leave Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #000;
            margin: 30px;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        p {
            margin: 0;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 6px 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .footer {
            position: fixed;
            bottom: 10px;
            font-size: 10px;
            text-align: center;
            width: 100%;
        }
    </style>
</head>

<body>

    <h2>Leave Report</h2>

    <p><strong>Generated At:</strong> {{ now()->format('d-m-Y H:i') }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Employee</th>
                <th>Leave Type</th>
                <th>From</th>
                <th>To</th>
                <th>Total Days</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($leaveRequests as $leave)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $leave->user->name }}</td>
                <td>{{ $leave->leaveType->name ?? '—' }}</td>
                <td>{{ \Carbon\Carbon::parse($leave->start_date)->format('d-m-Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($leave->end_date)->format('d-m-Y') }}</td>
                <td>{{ \Carbon\Carbon::parse($leave->start_date)->diffInDays(\Carbon\Carbon::parse($leave->end_date)) + 1 }}</td>
                <td>{{ ucfirst($leave->status) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Leave Management System | {{ config('app.name') }}
    </div>

</body>

</html>